<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var \Faslet\Connect\ViewModel\ProductWidget $viewModel */ ?>

<?php $viewModel = $block->getViewModel(); ?>
<?php if ($widgetData = $viewModel->getWidgetData()): ?>
    <?= /* @noEscape */ "<script>console.log(JSON.parse('" . json_encode($widgetData) . "'));</script>"; ?>
    <div class="faslet-widget-box">
        <faslet-app
                shop-id="<?= $escaper->escapeHtmlAttr($widgetData['shop']['id'] ?? ''); ?>"
                brand="<?= $escaper->escapeHtmlAttr($widgetData['product']['brand'] ?? ''); ?>"
                product-identifier="<?= $escaper->escapeHtmlAttr($widgetData['product']['id'] ?? ''); ?>"
                product-name="<?= $escaper->escapeHtmlAttr($widgetData['product']['name'] ?? ''); ?>"
                product-img="<?= $escaper->escapeHtmlAttr($widgetData['product']['image'] ?? ''); ?>"
                platform="Magento 2"
        />
    </div>

    <script type="text/x-magento-init">
         {
              "*": {
                  "Faslet_Connect/js/widget": {
                    "shopUrl": "<?= $escaper->escapeUrl($widgetData['shop']['url'] ?? ''); ?>",
                    "productId": "<?= $escaper->escapeJs($widgetData['product']['id'] ?? ''); ?>",
                    "productSku": "<?= $escaper->escapeJs($widgetData['product']['sku'] ?? ''); ?>",
                    "productVariants": <?= /* @noEscape */ json_encode($widgetData['product']['variants'] ?? []); ?>
                  }
              }
          }
    </script>
<?php endif; ?>
